name: Reusable Dependencies PR Workflow

on:
  workflow_call:
    # このワークフローは他のワークフローから呼び出せるように設定

jobs:
  reusable-job:
    if: ${{ ( github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'dependencies') ) || ( github.event.pull_request.user.login == 'dependabot[bot]' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello message
        run: echo "Hello, Reuseable Actions, Dependencies PR!" 